#ifdef ITER_DOLLAR_MACROS_DEFINE_HPP
#undef ITER_DOLLAR_MACROS_DEFINE_HPP

#include "extend/dollar_macros/undef.hpp"

#undef $to_iter
#undef $next
#undef $cycle
#undef $until
#undef $til
#undef $filter
#undef $take
#undef $take_while
#undef $skip
#undef $skip_while
#undef $flatten
#undef $flatmap
#undef $flat_map
#undef $filter_map
#undef $map
#undef $map_while
#undef $zip
#undef $enumerate
#undef $chain
#undef $chunks
#undef $inspect
#undef $to_pointer_iter
#undef $move
#undef $box
#undef $foreach
#undef $for_each
#undef $fold
#undef $fold_left
#undef $reduce
#undef $sum
#undef $product
#undef $last
#undef $nth
#undef $min
#undef $min_by
#undef $max
#undef $max_by
#undef $find_linear
#undef $find_map
#undef $any
#undef $all
#undef $to_vector
#undef $to_map
#undef $partition
#undef $unzip
#undef $chunks_
#undef $window
#undef $collect
#undef $partition_
#undef $unzip_
#undef $sorted_

#endif /* ITER_DOLLAR_MACROS_DEFINE_HPP */
