#!/bin/sh

cd "$(dirname "$0")"/../

X_MACROS_FILE=include/iter/x_macros/iter_functions_simple.ipp

cat > $X_MACROS_FILE <<- EOM
/* Do not modify, generated by scripts/update_x_macros.sh */

EOM

grep -oE '(ITER_DECLARE\([^\)]+\)$)|(ITER_ALIAS\([^,]+,.*\)$)' singleheader/iter.hpp \
    | grep -E -v '(to_iter|til|until|to_pointer_iter)' \
    | sed -E 's|ITER_DECLARE\((\w+)\)|// Invoke iter::\1 on this iter\nITER_X(\1)|g' \
    | sed -E 's|ITER_ALIAS\(([^,]+),\s*(.*)\)|// Invoke iter::\1 (aka iter::\2) on this iter\nITER_X(\1)|g' \
    >> $X_MACROS_FILE

X_MACROS_FILE=include/iter/x_macros/iter_functions_tmpl.ipp

cat > $X_MACROS_FILE <<- EOM
/* Do not modify, generated by scripts/update_x_macros.sh */

EOM

grep -Pzo 'template<(.*)>\n.*tag::(\w+)<(.*)> \w+;' singleheader/iter.hpp \
    | tr '\r\n' ';' \
    | tr '\0' ';' \
    | perl -pe 's#template<([^;]+)>;\s+static constexpr tag::\w+<([^>]+)>\s+(\w+)[;]+#// Invoke iter::\2 on this iter\nITER_X(\3, (\1), (\2))\n#g' \
    >> $X_MACROS_FILE
